import './globals.css';
import type { Metadata } from 'next';
import Providers from '@/components/layouts/Providers';
import { getLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { FONT_MONO, FONT_SANS } from '@/common/constants/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body className={`${FONT_SANS.variable} ${FONT_MONO.variable} antialiased`}>
        <NextIntlClientProvider locale={locale}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
