import { ActivityIcon, ChartBarIcon, Code2Icon, CodeIcon, FolderIcon, FolderKanbanIcon, KanbanSquareIcon, LayoutDashboardIcon, RocketIcon, SendIcon, UserCircleIcon, UserIcon } from 'lucide-react';

export const FEATURES = [
  {
    Icon: UserCircleIcon,
    name: 'Tell Your Story',
    description: 'About section to showcase who you are and what drives you.',
    href: '/',
    cta: 'Read More',
    background: <img className="absolute -right-20 -top-20 opacity-60" />,
    className: 'lg:col-start-1 lg:col-end-2 lg:row-start-1 lg:row-end-3',
  },
  {
    Icon: ActivityIcon,
    name: 'Insights Dashboard',
    description: 'A dashboard to present data, progress, or analytics in real-time.',
    href: '/',
    cta: 'Explore Dashboard',
    background: <img className="absolute -right-20 -top-20 opacity-60" />,
    className: 'lg:col-start-2 lg:col-end-4 lg:row-start-2 lg:row-end-3',
  },
  {
    Icon: Code2Icon,
    name: 'Show Your Skills',
    description: 'Highlight the tools, stacks, and technologies you excel at.',
    href: '/',
    cta: 'View Skills',
    background: <img className="absolute -right-20 -top-20 opacity-60" />,
    className: 'lg:col-start-2 lg:col-end-2 lg:row-start-1 lg:row-end-2',
  },
  {
    Icon: Code2Icon,
    name: 'Lihat Apa yang sedang dilakukan.',
    description: 'Apa yang sedang dilakukan dengan  API Discord Layard',
    href: '/',
    cta: 'View Skills',
    background: <img className="absolute -right-20 -top-20 opacity-60" />,
    className: 'lg:col-start-3 lg:col-end-3 lg:row-start-1 lg:row-end-2',
  },
  {
    Icon: FolderKanbanIcon,
    name: 'Projects',
    description: 'Curated projects to showcase your best work and case studies.',
    href: '/',
    cta: 'See Projects',
    background: <img className="absolute -right-20 -top-20 opacity-60" />,
    className: 'lg:col-start-1 lg:col-end-3 lg:row-start-3 lg:row-end-4',
  },
  {
    Icon: SendIcon,
    name: 'Stay Connected',
    description: '...',
    href: '/',
    cta: 'Connect',
    background: <img className="absolute -right-20 -top-20 opacity-60" />,
    className: 'lg:col-start-3 lg:col-end-3 lg:row-start-3 lg:row-end-4',
  },
];
